import { Request, Response, NextFunction } from 'express';
import { initializeApp, getApps, cert, applicationDefault, App } from 'firebase-admin/app';
import { getAuth, Auth } from 'firebase-admin/auth';
import { authService, UserRole } from '../services/authService';

export interface AuthenticatedRequest extends Request {
  userId?: string;
  userEmail?: string;
  userRole?: UserRole;
  userName?: string;
}

const DEFAULT_DEV_USER = 'usr_student_preview';

/**
 * Lazy initialization of Firebase Admin SDK
 * Safely loads credentials from environment or GCP Application Default Credentials (ADC)
 */
let firebaseApp: App | null = null;
let firebaseAuth: Auth | null = null;

function getFirebaseAuth(): Auth | null {
  if (firebaseAuth) return firebaseAuth;

  const projectId = process.env.FIREBASE_PROJECT_ID;
  const clientEmail = process.env.FIREBASE_CLIENT_EMAIL;
  const privateKey = process.env.FIREBASE_PRIVATE_KEY?.replace(/\\n/g, '\n');

  if (getApps().length > 0) {
    firebaseApp = getApps()[0];
    firebaseAuth = getAuth(firebaseApp);
    return firebaseAuth;
  }

  if (projectId && clientEmail && privateKey) {
    firebaseApp = initializeApp({
      credential: cert({
        projectId,
        clientEmail,
        privateKey,
      }),
    });
    firebaseAuth = getAuth(firebaseApp);
    return firebaseAuth;
  } else if (projectId) {
    // Uses Google Cloud Run metadata server / Application Default Credentials (ADC)
    firebaseApp = initializeApp({
      projectId,
      credential: applicationDefault(),
    });
    firebaseAuth = getAuth(firebaseApp);
    return firebaseAuth;
  }

  return null;
}

/**
 * Authentication Middleware:
 * Verifies Bearer session tokens generated by AuthService,
 * or cryptographic Firebase ID tokens if configured.
 */
export async function authenticateRequest(
  req: AuthenticatedRequest,
  res: Response,
  next: NextFunction
) {
  try {
    const authHeader = req.headers.authorization;
    let resolvedUserId: string | null = null;
    let resolvedEmail: string | undefined = undefined;
    let resolvedRole: UserRole = 'student';
    let resolvedName: string | undefined = undefined;

    if (authHeader && authHeader.startsWith('Bearer ')) {
      const token = authHeader.split('Bearer ')[1]?.trim();

      if (token) {
        // 1. Check native AuthService session token
        const session = authService.validateSession(token);
        if (session) {
          req.userId = session.userId;
          req.userEmail = session.email;
          req.userRole = session.role;
          req.userName = session.name;
          return next();
        }

        // 2. Check Firebase ID token if configured
        const auth = getFirebaseAuth();
        if (auth) {
          try {
            const decoded = await auth.verifyIdToken(token);
            resolvedUserId = decoded.uid;
            resolvedEmail = decoded.email;
            resolvedRole = (decoded.role as UserRole) || 'student';
          } catch {
            // Token was not a valid Firebase token
          }
        }
      }
    }

    // Allow x-user-id header in development for testing
    if (!resolvedUserId && req.headers['x-user-id'] && process.env.NODE_ENV !== 'production') {
      const headerUserId = String(req.headers['x-user-id']).trim();
      if (/^[a-zA-Z0-9_\-\.]{3,64}$/.test(headerUserId)) {
        resolvedUserId = headerUserId;
        const user = authService.getUserById(headerUserId);
        if (user) {
          resolvedEmail = user.email;
          resolvedRole = user.role;
          resolvedName = user.name;
        }
      }
    }

    // If still unresolved in dev/preview, fallback to demo student
    if (!resolvedUserId && process.env.NODE_ENV !== 'production') {
      resolvedUserId = DEFAULT_DEV_USER;
      const demoUser = authService.getUserById(DEFAULT_DEV_USER);
      if (demoUser) {
        resolvedEmail = demoUser.email;
        resolvedRole = demoUser.role;
        resolvedName = demoUser.name;
      }
    }

    if (!resolvedUserId) {
      return res.status(401).json({ error: 'Unauthorized: Valid session or token required.' });
    }

    req.userId = resolvedUserId;
    req.userEmail = resolvedEmail;
    req.userRole = resolvedRole;
    req.userName = resolvedName;

    next();
  } catch (error: any) {
    console.error('[AuthMiddleware] Verification error:', error.message);
    res.status(401).json({ error: 'Unauthorized: Authentication failed.' });
  }
}

/**
 * Strict role-based authorization guard
 */
export function requireRole(allowedRoles: UserRole[]) {
  return (req: AuthenticatedRequest, res: Response, next: NextFunction) => {
    if (!req.userId) {
      return res.status(401).json({ error: 'Authentication required.' });
    }
    const role = req.userRole || 'student';
    if (!allowedRoles.includes(role)) {
      return res.status(403).json({
        error: `Forbidden: Access restricted to roles: [${allowedRoles.join(', ')}]. Current role is '${role}'.`,
      });
    }
    next();
  };
}

/**
 * Require valid authenticated user
 */
export function requireAuth(req: AuthenticatedRequest, res: Response, next: NextFunction) {
  if (!req.userId) {
    return res.status(401).json({ error: 'Authentication required.' });
  }
  next();
}

