import express,{Request,Response,NextFunction} from 'express';
import multer from 'multer'; import path from 'path'; import fs from 'fs'; import {nanoid} from 'nanoid'; import mammoth from 'mammoth'; import sanitizeHtml from 'sanitize-html';
import {adminStore,PRIVATE_UPLOADS_DIR} from '../services/adminStore'; import {authService} from '../services/authService'; import {storageProvider} from '../services/storage';
export const adminRouter=express.Router();
type AdminRequest=Request&{adminUser?:{id:string;username:string;displayName:string;role:string}};
const isSection=(v:unknown):v is 'speaking'|'reading'|'listening'|'writing'=>['speaking','reading','listening','writing'].includes(String(v));
const BINARY_MAGIC_SIGNATURES=[[0x4d,0x5a],[0x7f,0x45,0x4c,0x46],[0xfe,0xed,0xfa,0xce],[0xfe,0xed,0xfa,0xcf],[0xca,0xfe,0xba,0xbe],[0x50,0x4b,0x03,0x04],[0x25,0x50,0x44,0x46],[0x89,0x50,0x4e,0x47,0x0d,0x0a,0x1a,0x0a],[0xff,0xd8,0xff],[0x47,0x49,0x46,0x38],[0x52,0x49,0x46,0x46],[0x1f,0x8b],[0x37,0x7a,0xbc,0xaf,0x27,0x1c],[0x52,0x61,0x72,0x21],[0xfd,0x37,0x7a,0x58,0x5a,0x00],[0x42,0x5a,0x68]];
export function validateHtmlFileBuffer(buffer:Buffer){if(!buffer?.length)return{valid:false,error:'File is empty.'};if(buffer.length>5*1024*1024)return{valid:false,error:'HTML file exceeds the 5MB size limit.'};for(const sig of BINARY_MAGIC_SIGNATURES)if(buffer.length>=sig.length&&sig.every((b,i)=>buffer[i]===b))return{valid:false,error:'Disguised binary file detected.'};if(buffer.includes(0))return{valid:false,error:'Binary null bytes detected.'};for(let i=0;i<Math.min(buffer.length,8192);i++){const b=buffer[i];if(b<9||b===11||b===12||(b>=14&&b<=31)||b===127)return{valid:false,error:'Unprintable binary control bytes detected.'};}try{const text=new TextDecoder('utf-8',{fatal:true}).decode(buffer);if(!/<(!DOCTYPE|html|head|body|p|div|table|h[1-6]|span|section|article|main|ul|ol|b|strong|em|i)\b/i.test(text))return{valid:false,error:'No recognized HTML structure found.'};}catch{return{valid:false,error:'Invalid UTF-8 byte sequence.'}}return{valid:true};}
const SAFE_CLASS_PATTERNS=[/^cdi-[\w-]+$/,/^text-(left|right|center|justify|xs|sm|base|lg|slate|gray|neutral|zinc|black|red|emerald|amber|indigo)$/,/^font-(serif|sans|mono|bold|semibold|normal|medium)$/,/^(italic|underline|line-through)$/,/^p[xytb]?-[0-8]$/,/^m[xytb]?-[0-8]$/,/^border(?:-[a-z0-9-]+)?$/,/^bg-[a-z0-9-]+$/,/^(table|table-[a-z]+|w-full|h-auto|max-w-[a-z0-9]+)$/,/^list-[a-z]+$/,/^space-[xy]-[0-8]$/];
const SAFE_STYLE_RULES:Record<string,RegExp>={'text-align':/^(left|right|center|justify)$/i,'vertical-align':/^(top|middle|bottom|baseline)$/i,'font-weight':/^(bold|normal|[1-9]00)$/i,'font-style':/^(italic|normal)$/i,'text-decoration':/^(underline|line-through|none)$/i,'width':/^\d+(?:\.\d+)?(?:px|%|em|rem|ch)$/i,'max-width':/^\d+(?:\.\d+)?(?:px|%|em|rem|ch)$/i,'min-width':/^\d+(?:\.\d+)?(?:px|%|em|rem|ch)$/i,'height':/^\d+(?:\.\d+)?(?:px|%|em|rem|ch)$/i,'padding':/^[0-9.]+(?:px|%|em|rem)(?:\s+[0-9.]+(?:px|%|em|rem))*$/i,'padding-left':/^[0-9.]+(?:px|%|em|rem)$/i,'padding-right':/^[0-9.]+(?:px|%|em|rem)$/i,'padding-top':/^[0-9.]+(?:px|%|em|rem)$/i,'padding-bottom':/^[0-9.]+(?:px|%|em|rem)$/i,'margin':/^(auto|[0-9.]+(?:px|%|em|rem)(?:\s+[0-9.]+(?:px|%|em|rem))*)$/i,'margin-left':/^(auto|[0-9.]+(?:px|%|em|rem))$/i,'margin-right':/^(auto|[0-9.]+(?:px|%|em|rem))$/i,'margin-top':/^(auto|[0-9.]+(?:px|%|em|rem))$/i,'margin-bottom':/^(auto|[0-9.]+(?:px|%|em|rem))$/i,'border':/^[0-9a-zA-Z\s#(),.-]+$/i,'border-top':/^[0-9a-zA-Z\s#(),.-]+$/i,'border-bottom':/^[0-9a-zA-Z\s#(),.-]+$/i,'border-left':/^[0-9a-zA-Z\s#(),.-]+$/i,'border-right':/^[0-9a-zA-Z\s#(),.-]+$/i,'border-collapse':/^(collapse|separate)$/i,'border-spacing':/^[0-9px\s]+$/i,'color':/^(#[0-9a-fA-F]{3,8}|rgb\([0-9\s,]+\)|rgba\([0-9\s,.]+\)|[a-zA-Z]+)$/i,'background-color':/^(#[0-9a-fA-F]{3,8}|rgb\([0-9\s,]+\)|rgba\([0-9\s,.]+\)|transparent|[a-zA-Z]+)$/i};
const sanitizeClass=(value:string)=>value.split(/\s+/).filter(v=>SAFE_CLASS_PATTERNS.some(p=>p.test(v))).join(' ');
const sanitizeStyle=(value:string)=>value.split(';').map(part=>{const [key,...rest]=part.split(':');const prop=key?.trim().toLowerCase();const val=rest.join(':').trim();return prop&&val&&SAFE_STYLE_RULES[prop]?.test(val)&&!/[()@]|url|expression|javascript/i.test(val)?`${prop}:${val}`:''}).filter(Boolean).join(';');
export const sanitizeHtmlServer=(rawHtml:string)=>sanitizeHtml(typeof rawHtml==='string'?rawHtml:'',{allowedTags:['h1','h2','h3','h4','h5','h6','p','br','hr','strong','b','em','i','u','s','del','mark','small','sub','sup','span','div','blockquote','q','pre','code','ul','ol','li','dl','dt','dd','table','thead','tbody','tfoot','tr','th','td','caption','col','colgroup','img','a','figure','figcaption','section','article','aside','header','footer','nav','main','details','summary'],allowedAttributes:{'*':['class','id','style','title','lang','dir'],img:['src','alt','width','height','loading'],a:['href','target','rel'],th:['colspan','rowspan','headers','scope'],td:['colspan','rowspan','headers','scope']},allowedStyles:{'*':SAFE_STYLE_RULES},allowedSchemes:['http','https','mailto','data'],allowedSchemesByTag:{img:['data']},allowProtocolRelative:false,transformTags:{img:(tagName,attribs)=>{const src=(attribs.src||'').trim();const local=src.startsWith('/api/uploads/');const inline=/^data:image\/(png|jpeg|jpg|webp|gif);base64,/i.test(src);if(!local&&!inline)return{tagName:'span',attribs:{class:'cdi-blocked-img text-slate-400 italic text-xs block my-2 p-2 border border-dashed border-slate-300 rounded bg-slate-50'},text:'[External image blocked]'};return{tagName,attribs};},a:(tagName,attribs)=>{attribs.target='_blank';attribs.rel='noopener noreferrer nofollow';return{tagName,attribs};},'*':(tagName,attribs)=>{if(typeof attribs.class==='string')attribs.class=sanitizeClass(attribs.class);if(typeof attribs.style==='string')attribs.style=sanitizeStyle(attribs.style);return{tagName,attribs};}},disallowedTagsMode:'discard'});
export function deepSanitizeHtml(obj:any):any{if(!obj||typeof obj!=='object')return obj;if(Array.isArray(obj))return obj.map(deepSanitizeHtml);const out:any={};for(const[k,v]of Object.entries(obj))out[k]=(k==='htmlContent'||k==='passageHtml')&&typeof v==='string'?sanitizeHtmlServer(v):v&&typeof v==='object'?deepSanitizeHtml(v):v;return out;}
export async function requireAdminAuth(req:AdminRequest,res:Response,next:NextFunction){try{const h=req.headers.authorization;if(!h?.startsWith('Bearer '))return res.status(403).json({error:'Forbidden.'});const s=await authService.validateSession(h.slice(7).trim());if(!s||(s.role!=='admin'&&s.role!=='examiner'))return res.status(403).json({error:'Forbidden.'});req.adminUser={id:s.userId,username:s.username,displayName:s.name,role:s.role};return next();}catch{return res.status(403).json({error:'Forbidden.'});}}
export function requireAdminRole(req:AdminRequest,res:Response,next:NextFunction){if(req.adminUser?.role!=='admin')return res.status(403).json({error:'Administrator role required.'});return next();}
const diskStorage=multer.diskStorage({destination:(_r,_f,cb)=>cb(null,PRIVATE_UPLOADS_DIR),filename:(_r,file,cb)=>{const ext=path.extname(file.originalname).toLowerCase();const base=path.basename(file.originalname,ext).replace(/[^a-zA-Z0-9_-]/g,'_').slice(0,80)||'upload';cb(null,`${base}_${Date.now()}-${nanoid(8)}${ext}`);}});
const fileFilter:multer.Options['fileFilter']=(_r,file,cb)=>cb(['.mp3','.wav','.ogg','.png','.jpg','.jpeg','.webp','.pdf','.docx','.txt','.html','.htm'].includes(path.extname(file.originalname).toLowerCase())?null:new Error('Unsupported file type.'));
const upload=multer({storage:diskStorage,fileFilter,limits:{fileSize:35*1024*1024,files:1,fields:20,fieldNameSize:100,fieldSize:256*1024,parts:22}});
adminRouter.post('/login',async(req,res)=>{try{const r=await authService.login(String(req.body?.username||''),String(req.body?.password||''));if(r.user.role!=='admin'&&r.user.role!=='examiner')return res.status(403).json({error:'Forbidden.'});return res.json({success:true,token:r.token,admin:{username:r.user.username,displayName:r.user.name,role:r.user.role}});}catch{return res.status(401).json({error:'Invalid credentials.'});}});
adminRouter.get('/me',requireAdminAuth,(req:AdminRequest,res)=>res.json({admin:req.adminUser}));
adminRouter.post('/logout',requireAdminAuth,async(req:AdminRequest,res)=>{try{const h=req.headers.authorization;if(h?.startsWith('Bearer '))await authService.logout(h.slice(7).trim());}catch{}return res.json({success:true});});
adminRouter.get('/files/:filename',requireAdminAuth,async(req,res)=>{try{const filename=path.basename(req.params.filename);const record=await adminStore.getFileRecord(filename);if(!record)return res.status(404).json({error:'File not found.'});const key=String(record.storagePath||'');if(process.env.NODE_ENV==='production'||process.env.STORAGE_BACKEND==='gcs_firestore'){const data=await storageProvider.downloadFile(key);res.type(record.mimetype||'application/octet-stream').set('Content-Disposition',`inline; filename="${filename.replace(/"/g,'')}"`).send(data);return;}const full=path.resolve(PRIVATE_UPLOADS_DIR,filename);if(!full.startsWith(path.resolve(PRIVATE_UPLOADS_DIR)+path.sep)||!fs.existsSync(full))return res.status(404).json({error:'File not found.'});return res.sendFile(full);}catch{return res.status(404).json({error:'File not found.'});}});
adminRouter.get('/stats',requireAdminAuth,async(_req,res)=>{try{return res.json({stats:await adminStore.getStats()});}catch{return res.status(500).json({error:'Unable to load stats.'});}});
adminRouter.post('/upload',requireAdminAuth,requireAdminRole,upload.single('file'),async(req:AdminRequest,res)=>{const file=(req as any).file;if(!file)return res.status(400).json({error:'No file was uploaded.'});try{let extractedText='',extractedHtml='';const ext=path.extname(file.originalname).toLowerCase();if(ext==='.html'||ext==='.htm'){const b=fs.readFileSync(file.path),v=validateHtmlFileBuffer(b);if(!v.valid){fs.unlinkSync(file.path);return res.status(400).json({error:v.error});}extractedHtml=sanitizeHtmlServer(b.toString('utf8'));fs.writeFileSync(file.path,extractedHtml,'utf8');extractedText=extractedHtml.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim();}else if(ext==='.txt'){const b=fs.readFileSync(file.path);if(b.includes(0)){fs.unlinkSync(file.path);return res.status(400).json({error:'Binary text file rejected.'});}extractedText=b.toString('utf8');}else if(ext==='.docx'){const r=await mammoth.extractRawText({path:file.path});extractedText=r.value||'';}else if(ext==='.pdf'){try{const mod=await import('pdf-parse');const fn=(mod as any).default||(mod as any).PDFParse||mod;if(typeof fn==='function'){const r=await fn(fs.readFileSync(file.path));extractedText=r.text||'';}}catch{}}
const isCloud=process.env.NODE_ENV==='production'||process.env.STORAGE_BACKEND==='gcs_firestore';const storagePath=isCloud?`admin_uploads/${file.filename}`:file.filename;if(isCloud){await storageProvider.uploadFile(storagePath,fs.readFileSync(file.path),file.mimetype);try{fs.unlinkSync(file.path)}catch{}}await adminStore.saveFileRecord({filename:file.filename,originalName:file.originalname,size:file.size,mimetype:file.mimetype,storagePath,createdAt:new Date().toISOString(),createdBy:req.adminUser?.id||'admin'});return res.json({success:true,file:{filename:file.filename,originalName:file.originalname,size:file.size,mimetype:file.mimetype,url:`/api/admin/files/${encodeURIComponent(file.filename)}`,extractedHtml:extractedHtml||undefined,extractedText:extractedText.trim()||undefined}});}catch{try{fs.unlinkSync(file.path)}catch{}return res.status(500).json({error:'File upload failed.'});}});
adminRouter.get('/materials',requireAdminAuth,async(req,res)=>{const status=['all','published','draft'].includes(String(req.query.status))?String(req.query.status) as any:undefined;const s=req.query.section;if(isSection(s))return res.json({items:await adminStore.listMaterials(s,status)});return res.json({items:(await Promise.all((['speaking','reading','listening','writing'] as const).map(x=>adminStore.listMaterials(x,status)))).flat()});});
adminRouter.get('/materials/:section/:id',requireAdminAuth,async(req,res)=>{if(!isSection(req.params.section))return res.status(400).json({error:'Invalid section.'});const item=await adminStore.getMaterial(req.params.section,req.params.id);return item?res.json({item}):res.status(404).json({error:'Material not found.'});});
adminRouter.post('/materials',requireAdminAuth,requireAdminRole,async(req:AdminRequest,res)=>{if(!isSection(req.body?.section))return res.status(400).json({error:'Valid section is required.'});const body=deepSanitizeHtml(req.body);return res.json({success:true,item:await adminStore.saveMaterial(req.body.section,body,req.adminUser?.displayName||'Admin')});});
adminRouter.post('/materials/:section',requireAdminAuth,requireAdminRole,async(req:AdminRequest,res)=>{if(!isSection(req.params.section))return res.status(400).json({error:'Invalid section.'});return res.json({success:true,item:await adminStore.saveMaterial(req.params.section,deepSanitizeHtml(req.body),req.adminUser?.displayName||'Admin')});});
adminRouter.put('/materials/:id',requireAdminAuth,requireAdminRole,async(req:AdminRequest,res)=>{if(!isSection(req.body?.section))return res.status(400).json({error:'Valid section is required.'});return res.json({success:true,item:await adminStore.saveMaterial(req.body.section,{...deepSanitizeHtml(req.body),id:req.params.id},req.adminUser?.displayName||'Admin')});});
adminRouter.put('/materials/:section/:id',requireAdminAuth,requireAdminRole,async(req:AdminRequest,res)=>{if(!isSection(req.params.section))return res.status(400).json({error:'Invalid section.'});return res.json({success:true,item:await adminStore.saveMaterial(req.params.section,{...deepSanitizeHtml(req.body),id:req.params.id},req.adminUser?.displayName||'Admin')});});
adminRouter.delete('/materials/:id',requireAdminAuth,requireAdminRole,async(req,res)=>{for(const s of ['speaking','reading','listening','writing'] as const)if(await adminStore.deleteMaterial(s,req.params.id))return res.json({success:true});return res.status(404).json({error:'Material not found.'});});
adminRouter.delete('/materials/:section/:id',requireAdminAuth,requireAdminRole,async(req,res)=>{if(!isSection(req.params.section))return res.status(400).json({error:'Invalid section.'});return await adminStore.deleteMaterial(req.params.section,req.params.id)?res.json({success:true}):res.status(404).json({error:'Material not found.'});});
adminRouter.get('/bundles',requireAdminAuth,async(req,res)=>res.json({bundles:await adminStore.listBundles(['all','published','draft'].includes(String(req.query.status))?String(req.query.status) as any:undefined)}));
adminRouter.get('/bundles/:id',requireAdminAuth,async(req,res)=>{const x=await adminStore.getResolvedBundle(req.params.id);return x?res.json(x):res.status(404).json({error:'CDI Bundle not found.'});});
adminRouter.post('/bundles',requireAdminAuth,requireAdminRole,async(req,res)=>res.json({success:true,bundle:await adminStore.saveBundle(deepSanitizeHtml(req.body))}));
adminRouter.put('/bundles/:id',requireAdminAuth,requireAdminRole,async(req,res)=>res.json({success:true,bundle:await adminStore.saveBundle({...deepSanitizeHtml(req.body),id:req.params.id})}));
adminRouter.delete('/bundles/:id',requireAdminAuth,requireAdminRole,async(req,res)=>await adminStore.deleteBundle(req.params.id)?res.json({success:true}):res.status(404).json({error:'Bundle not found.'}));
adminRouter.get('/public/materials/:section',async(req,res)=>{if(!isSection(req.params.section))return res.status(400).json({error:'Invalid section.'});return res.json({items:await adminStore.listMaterials(req.params.section,'published')});});
adminRouter.get('/public/bundles',async(_req,res)=>res.json({bundles:await adminStore.listBundles('published')}));
adminRouter.get('/public/bundles/:id',async(req,res)=>{const x=await adminStore.getResolvedBundle(req.params.id);return x&&x.bundle.status==='published'?res.json(x):res.status(404).json({error:'Published CDI exam not found.'});});
