import { Router, Request, Response } from 'express';
import { authService } from '../services/authService';

export const authRouter = Router();
const isObj=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v);
const bearer=(req:Request)=>{const h=req.headers.authorization;return h?.startsWith('Bearer ')?h.slice(7).trim():'';};

authRouter.post('/register',async(req,res)=>{try{if(!isObj(req.body))return res.status(400).json({error:'Invalid request.'});const r=await authService.register({email:String(req.body.email||''),username:String(req.body.username||''),password:String(req.body.password||''),name:req.body.name==null?undefined:String(req.body.name)});return res.status(201).json({success:true,message:'Account created successfully.',user:r.user,token:r.token});}catch{return res.status(400).json({error:'Unable to create account.'});}});
authRouter.post('/login',async(req,res)=>{try{if(!isObj(req.body))return res.status(400).json({error:'Invalid request.'});const r=await authService.login(String(req.body.username||''),String(req.body.password||''));return res.json({success:true,message:'Logged in successfully.',user:r.user,token:r.token});}catch{return res.status(401).json({error:'Invalid credentials.'});}});
authRouter.post('/logout',async(req,res)=>{try{const token=bearer(req);if(token)await authService.logout(token);}catch{}return res.json({success:true,message:'Logged out successfully.'});});
authRouter.get('/me',async(req,res)=>{try{const token=bearer(req);const session=token?await authService.validateSession(token):null;if(!session)return res.status(401).json({error:'Unauthorized.'});const user=await authService.getUserById(session.userId);if(!user)return res.status(404).json({error:'User profile not found.'});return res.json({user});}catch{return res.status(401).json({error:'Unauthorized.'});}});
authRouter.post('/forgot-password',async(req,res)=>{try{const email=isObj(req.body)?String(req.body.email||''):'';const r=await authService.requestPasswordReset(email);const out:Record<string,unknown>={success:true,message:'If an account exists for this email, recovery instructions will be sent.',expiresMinutes:r.expiresMinutes};if(process.env.EXPLICIT_DEV_AUTH==='true'&&r.resetToken)out.devResetToken=r.resetToken;return res.json(out);}catch{return res.json({success:true,message:'If an account exists for this email, recovery instructions will be sent.'});}});
authRouter.post('/reset-password',async(req,res)=>{try{if(!isObj(req.body))return res.status(400).json({error:'Invalid request.'});await authService.resetPassword(String(req.body.email||''),String(req.body.token||''),String(req.body.newPassword||''));return res.json({success:true,message:'Password successfully reset.'});}catch{return res.status(400).json({error:'Invalid or expired reset token.'});}});
