import { Router, Request, Response } from 'express';
import { authService, AuthError } from '../services/authService';
import { requestRateLimitService, AuthRateLimitOperation } from '../services/requestRateLimitService';
import { AUTH_COOKIE } from '../middleware/authMiddleware';
import { guardAsyncHandlers } from '../http/asyncHandlers';
import { isStorageUnavailableError } from '../services/storage/availability';

// Each route answers its own refusals (a wrong password, a taken name, an expired
// token) as before. A user store that cannot be reached is not one of them: it goes
// to the API error boundary, which answers 503 rather than "invalid credentials".
export const authRouter = guardAsyncHandlers(Router());
const isObj=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v);
const readCookie=(req:Request,name:string)=>{const header=req.headers.cookie||'';for(const part of header.split(';')){const [k,...v]=part.trim().split('=');if(k===name)return decodeURIComponent(v.join('='));}return '';};
const clientKey=(req:Request,operation:AuthRateLimitOperation)=>`${operation}:${req.ip||'unknown'}`;
const enforceRateLimit=async(req:Request,res:Response,operation:AuthRateLimitOperation)=>{const result=await requestRateLimitService.check(clientKey(req,operation),operation);if(result.allowed)return true;res.setHeader('Retry-After',String(Math.max(1,Math.ceil(result.retryAfterMs/1000))));res.status(429).json({error:'Too many requests. Please try again later.'});return false;};
const setAuthCookie=(res:Response,token:string,maxAge:number)=>res.cookie(AUTH_COOKIE,token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'strict',path:'/',maxAge});
const clearAuthCookie=(res:Response)=>res.clearCookie(AUTH_COOKIE,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'strict',path:'/'});
const sessionMaxAge=(role:string)=>role==='student'?7*24*60*60*1000:24*60*60*1000;

authRouter.post('/register',async(req,res,next)=>{try{if(!await enforceRateLimit(req,res,'register'))return;if(!isObj(req.body))return res.status(400).json({error:'Invalid request.'});const r=await authService.register({email:String(req.body.email||''),username:String(req.body.username||''),password:String(req.body.password||''),name:req.body.name==null?undefined:String(req.body.name)});setAuthCookie(res,r.token,sessionMaxAge(r.user.role));return res.status(201).json({success:true,message:'Account created successfully.',user:r.user});}catch(error){if(isStorageUnavailableError(error))return next(error);const code=error instanceof AuthError?error.code:'unknown';if(code==='unknown')console.error('[Auth] registration failed:',error);else console.warn('[Auth] registration rejected:',code);return res.status(400).json({error:'Unable to create account.',code});}});
authRouter.post('/login',async(req,res,next)=>{try{if(!await enforceRateLimit(req,res,'login'))return;if(!isObj(req.body))return res.status(400).json({error:'Invalid request.'});const r=await authService.login(String(req.body.username||''),String(req.body.password||''));setAuthCookie(res,r.token,sessionMaxAge(r.user.role));return res.json({success:true,message:'Logged in successfully.',user:r.user});}catch(error){if(isStorageUnavailableError(error))return next(error);return res.status(401).json({error:'Invalid credentials.'});}});
authRouter.post('/logout',async(req,res)=>{try{const cookie=readCookie(req,AUTH_COOKIE);if(cookie)await authService.logout(cookie);}catch{}clearAuthCookie(res);return res.json({success:true,message:'Logged out successfully.'});});
authRouter.get('/me',async(req,res,next)=>{try{const sessionToken=readCookie(req,AUTH_COOKIE);const session=sessionToken?await authService.validateSession(sessionToken):null;if(!session)return res.status(401).json({error:'Unauthorized.'});const user=await authService.getUserById(session.userId);if(!user)return res.status(404).json({error:'User profile not found.'});return res.json({user});}catch(error){if(isStorageUnavailableError(error))return next(error);return res.status(401).json({error:'Unauthorized.'});}});
authRouter.post('/forgot-password',async(req,res,next)=>{try{if(!await enforceRateLimit(req,res,'forgot_password'))return;const email=isObj(req.body)?String(req.body.email||''):'';const r=await authService.requestPasswordReset(email);const out:Record<string,unknown>={success:true,message:'If an account exists for this email, recovery instructions will be sent.',expiresMinutes:r.expiresMinutes};if(process.env.NODE_ENV!=='production'&&process.env.EXPLICIT_DEV_AUTH==='true'&&r.resetToken)out.devResetToken=r.resetToken;return res.json(out);}catch(error){if(isStorageUnavailableError(error))return next(error);return res.json({success:true,message:'If an account exists for this email, recovery instructions will be sent.'});}});
authRouter.post('/reset-password',async(req,res,next)=>{try{if(!await enforceRateLimit(req,res,'reset_password'))return;if(!isObj(req.body))return res.status(400).json({error:'Invalid request.'});await authService.resetPassword(String(req.body.email||''),String(req.body.token||''),String(req.body.newPassword||''));clearAuthCookie(res);return res.json({success:true,message:'Password successfully reset.'});}catch(error){if(isStorageUnavailableError(error))return next(error);return res.status(400).json({error:'Invalid or expired reset token.'});}});
