import fs from 'fs';
import path from 'path';
import { nanoid } from 'nanoid';
import { getFirestoreDb } from './firebaseAdmin';
import { FieldValue } from 'firebase-admin/firestore';
import { AdminSpeakingMaterial, AdminReadingMaterial, AdminListeningMaterial, AdminWritingMaterial, FullCdiBundle, AdminStats } from '../types/admin';

const DATA_DIR = path.join(process.cwd(), 'data', 'admin_content');
const PRIVATE_UPLOADS_DIR = path.join(process.cwd(), 'data', 'private_uploads');
const PUBLIC_UPLOADS_DIR = path.join(process.cwd(), 'data', 'uploads');
const useFirestore = () => process.env.NODE_ENV === 'production' || process.env.STORAGE_BACKEND === 'gcs_firestore';
if (!useFirestore()) {
  if (!fs.existsSync(DATA_DIR)) fs.mkdirSync(DATA_DIR, { recursive: true });
  if (!fs.existsSync(PRIVATE_UPLOADS_DIR)) fs.mkdirSync(PRIVATE_UPLOADS_DIR, { recursive: true });
  if (!fs.existsSync(PUBLIC_UPLOADS_DIR)) fs.mkdirSync(PUBLIC_UPLOADS_DIR, { recursive: true });
}

type SectionType = 'speaking' | 'reading' | 'listening' | 'writing';
const assertId = (v:string) => { if (!/^[A-Za-z0-9_.-]{1,160}$/.test(v)) throw new Error('Invalid identifier.'); };

class AdminStore {
  private getFilePath(collection:string){return path.join(DATA_DIR,`${collection}.json`);}
  private readCollection<T>(collection:string):T[]{const filePath=this.getFilePath(collection);try{if(!fs.existsSync(filePath)){fs.writeFileSync(filePath,'[]','utf-8');return [];}const value=JSON.parse(fs.readFileSync(filePath,'utf-8'));return Array.isArray(value)?value as T[]:[];}catch{return [];}}
  private writeCollection<T>(collection:string,items:T[]):void{const filePath=this.getFilePath(collection),tmp=`${filePath}.tmp.${process.pid}.${Date.now()}.${nanoid(4)}`;fs.writeFileSync(tmp,JSON.stringify(items,null,2),'utf-8');fs.renameSync(tmp,filePath);}
  private async firestoreList<T>(section:string,statusFilter?:'all'|'published'|'draft'):Promise<T[]>{let q:any=getFirestoreDb().collection('admin_content').doc(section).collection('items');if(statusFilter&&statusFilter!=='all')q=q.where('status','==',statusFilter);const s=await q.get();return s.docs.map((d:any)=>d.data() as T);}
  public async listMaterials(section:SectionType,statusFilter?:'all'|'published'|'draft'):Promise<any[]>{return useFirestore()?this.firestoreList<any>(section,statusFilter):this.readCollection<any>(section).filter(x=>!statusFilter||statusFilter==='all'||x.status===statusFilter);}
  public async getMaterial(section:SectionType,id:string):Promise<any|null>{assertId(id);if(useFirestore()){const s=await getFirestoreDb().collection('admin_content').doc(section).collection('items').doc(id).get();return s.exists?s.data()||null:null;}return this.readCollection<any>(section).find(item=>item.id===id)||null;}
  public async saveMaterial(section:SectionType,materialData:any,author='Admin'):Promise<any>{assertId(section);const now=new Date().toISOString();if(useFirestore()){const db=getFirestoreDb(),id=materialData.id?String(materialData.id):`adm-${section.slice(0,3)}-${Date.now()}-${nanoid(5)}`;assertId(id);const ref=db.collection('admin_content').doc(section).collection('items').doc(id),existing=await ref.get();const item=existing.exists?{...(existing.data()||{}),...materialData,id,section,updatedAt:now}:{...materialData,id,section,status:materialData.status||'published',author:materialData.author||author,createdAt:now,updatedAt:now};await ref.set(item,{merge:true});return item;}const items=this.readCollection<any>(section);if(materialData.id){const index=items.findIndex(x=>x.id===materialData.id);if(index>=0){const updated={...items[index],...materialData,updatedAt:now};items[index]=updated;this.writeCollection(section,items);return updated;}}const item={...materialData,id:materialData.id||`adm-${section.slice(0,3)}-${Date.now()}-${nanoid(5)}`,section,status:materialData.status||'published',author:materialData.author||author,createdAt:now,updatedAt:now};items.unshift(item);this.writeCollection(section,items);return item;}
  public async deleteMaterial(section:SectionType,id:string){assertId(id);if(useFirestore()){const ref=getFirestoreDb().collection('admin_content').doc(section).collection('items').doc(id),snap=await ref.get();if(!snap.exists)return false;await ref.delete();return true;}const items=this.readCollection<any>(section),filtered=items.filter(x=>x.id!==id);if(filtered.length===items.length)return false;this.writeCollection(section,filtered);return true;}
  public async listBundles(statusFilter?:'all'|'published'|'draft'):Promise<FullCdiBundle[]>{return useFirestore()?this.firestoreList<FullCdiBundle>('bundles',statusFilter):this.readCollection<FullCdiBundle>('bundles').filter(x=>!statusFilter||statusFilter==='all'||x.status===statusFilter);}
  public async getBundle(id:string):Promise<FullCdiBundle|null>{assertId(id);if(useFirestore()){const s=await getFirestoreDb().collection('admin_content').doc('bundles').collection('items').doc(id).get();return s.exists?s.data() as FullCdiBundle:null;}return this.readCollection<FullCdiBundle>('bundles').find(x=>x.id===id)||null;}
  public async saveBundle(bundleData:Partial<FullCdiBundle>):Promise<FullCdiBundle>{const now=new Date().toISOString();if(useFirestore()){const db=getFirestoreDb(),id=String(bundleData.id||`cdi-bundle-${Date.now()}-${nanoid(5)}`);assertId(id);const ref=db.collection('admin_content').doc('bundles').collection('items').doc(id),existing=await ref.get();const item=(existing.exists?{...(existing.data()||{}),...bundleData,id,updatedAt:now}:{id,title:bundleData.title||'Untitled IELTS Full CDI Test',module:bundleData.module||'academic',targetBand:bundleData.targetBand||'7.0-7.5',status:bundleData.status||'draft',description:bundleData.description||'',createdAt:now,updatedAt:now,timings:bundleData.timings||{listeningMinutes:30,readingMinutes:60,writingMinutes:60,speakingMinutes:15},materials:bundleData.materials||{}}) as FullCdiBundle;await ref.set(item,{merge:true});return item;}const items=this.readCollection<FullCdiBundle>('bundles');if(bundleData.id){const index=items.findIndex(b=>b.id===bundleData.id);if(index>=0){const updated={...items[index],...bundleData,updatedAt:now} as FullCdiBundle;items[index]=updated;this.writeCollection('bundles',items);return updated;}}const item={id:bundleData.id||`cdi-bundle-${Date.now()}-${nanoid(5)}`,title:bundleData.title||'Untitled IELTS Full CDI Test',module:bundleData.module||'academic',targetBand:bundleData.targetBand||'7.0-7.5',status:bundleData.status||'draft',description:bundleData.description||'',createdAt:now,updatedAt:now,timings:bundleData.timings||{listeningMinutes:30,readingMinutes:60,writingMinutes:60,speakingMinutes:15},materials:bundleData.materials||{}} as FullCdiBundle;items.unshift(item);this.writeCollection('bundles',items);return item;}
  public async deleteBundle(id:string){assertId(id);if(useFirestore()){const ref=getFirestoreDb().collection('admin_content').doc('bundles').collection('items').doc(id),s=await ref.get();if(!s.exists)return false;await ref.delete();return true;}const items=this.readCollection<FullCdiBundle>('bundles'),filtered=items.filter(x=>x.id!==id);if(filtered.length===items.length)return false;this.writeCollection('bundles',filtered);return true;}
  public async getResolvedBundle(id:string){const bundle=await this.getBundle(id);if(!bundle)return null;const [listening,reading,writing,speaking]=await Promise.all([bundle.materials.listeningId?this.getMaterial('listening',bundle.materials.listeningId):Promise.resolve(null),bundle.materials.readingId?this.getMaterial('reading',bundle.materials.readingId):Promise.resolve(null),bundle.materials.writingId?this.getMaterial('writing',bundle.materials.writingId):Promise.resolve(null),bundle.materials.speakingId?this.getMaterial('speaking',bundle.materials.speakingId):Promise.resolve(null)]);return{bundle,resolvedMaterials:{listening,reading,writing,speaking}};}
  public async saveFileRecord(file:{filename:string;originalName:string;size:number;mimetype:string;storagePath:string;createdAt:string;createdBy:string}){if(useFirestore()){await getFirestoreDb().collection('admin_files').doc(file.filename).set({...file,updatedAt:FieldValue.serverTimestamp()});return;}const records=this.readCollection<any>('files');records.unshift(file);this.writeCollection('files',records);}
  public async getFileRecord(filename:string){assertId(filename.replace(/\.[^.]+$/,''));if(useFirestore()){const s=await getFirestoreDb().collection('admin_files').doc(filename).get();return s.exists?s.data()||null:null;}return this.readCollection<any>('files').find(x=>x.filename===filename)||null;}
  public async getStats():Promise<AdminStats>{const [speaking,reading,listening,writing,bundles]=await Promise.all([this.listMaterials('speaking'),this.listMaterials('reading'),this.listMaterials('listening'),this.listMaterials('writing'),this.listBundles()]);let fileCount=0,totalBytes=0;if(useFirestore()){const snap=await getFirestoreDb().collection('admin_files').get();fileCount=snap.size;snap.docs.forEach(d=>{totalBytes+=Number(d.data().size||0);});}else if(fs.existsSync(PRIVATE_UPLOADS_DIR))for(const f of fs.readdirSync(PRIVATE_UPLOADS_DIR))try{totalBytes+=fs.statSync(path.join(PRIVATE_UPLOADS_DIR,f)).size;fileCount++;}catch{}const all=[...speaking,...reading,...listening,...writing];return{totalMaterials:all.length,publishedMaterials:all.filter(m=>m.status==='published').length,draftMaterials:all.filter(m=>m.status==='draft').length,bySection:{speaking:speaking.length,reading:reading.length,listening:listening.length,writing:writing.length},totalBundles:bundles.length,uploadedFilesCount:fileCount,uploadedTotalBytes:totalBytes};}
}
export const adminStore=new AdminStore();
export const UPLOADS_DIR=PUBLIC_UPLOADS_DIR;
export {PRIVATE_UPLOADS_DIR,PUBLIC_UPLOADS_DIR};
