import fs from 'fs';
import path from 'path';
import bcrypt from 'bcryptjs';
import { nanoid } from 'nanoid';
import crypto from 'crypto';
import { getFirestoreDb } from './firebaseAdmin';
import { FieldValue } from 'firebase-admin/firestore';
import { isEmailDeliveryConfigured, sendPasswordResetEmail } from './emailService';

export type UserRole = 'student' | 'examiner' | 'admin';

/**
 * Registration failures carry a machine-readable code so the sign-up form can
 * tell the person which field to fix. The codes are deliberately coarse:
 * `already_exists` covers both a taken username and a taken email so the
 * endpoint cannot be used to enumerate registered addresses.
 */
export type AuthErrorCode =
  | 'invalid_email'
  | 'invalid_username'
  | 'weak_password'
  | 'already_exists';

export class AuthError extends Error {
  constructor(public readonly code: AuthErrorCode) {
    super(code);
    this.name = 'AuthError';
  }
}
export interface UserAccount { id:string; email:string; username:string; name:string; passwordHash:string; role:UserRole; createdAt:string; updatedAt:string; failedLoginAttempts:number; lockoutUntil?:number; resetTokenHash?:string; resetTokenExpiresAt?:number; sessionVersion?:number; }
export interface UserSession { token:string; userId:string; username:string; email:string; name:string; role:UserRole; createdAt:number; expiresAt:number; sessionVersion:number; }
const DATA_DIR=path.join(process.cwd(),'data');
const USERS_FILE=path.join(DATA_DIR,'users.json'); const SESSIONS_FILE=path.join(DATA_DIR,'sessions.json');
const MAX_FAILED_ATTEMPTS=5; const LOCKOUT_DURATION_MS=15*60*1000; const SESSION_TTL_STUDENT_MS=7*24*60*60*1000; const SESSION_TTL_ADMIN_MS=24*60*60*1000; const PASSWORD_RESET_TTL_MS=15*60*1000;
const useFirestoreAuth=()=>process.env.NODE_ENV==='production'||process.env.STORAGE_BACKEND==='gcs_firestore';
const hashToken=(token:string)=>crypto.createHash('sha256').update(token).digest('hex');
const explicitDevAuth=()=>process.env.EXPLICIT_DEV_AUTH==='true';
class AuthService{
 constructor(){if(!useFirestoreAuth()){fs.mkdirSync(DATA_DIR,{recursive:true});if(!fs.existsSync(USERS_FILE))fs.writeFileSync(USERS_FILE,'[]','utf8');if(!fs.existsSync(SESSIONS_FILE))fs.writeFileSync(SESSIONS_FILE,'{}','utf8');this.seedInitialAccounts();}}
 private readUsers():UserAccount[]{try{return JSON.parse(fs.readFileSync(USERS_FILE,'utf8'));}catch{return[]}}
 private writeUsers(users:UserAccount[]){const t=`${USERS_FILE}.tmp.${process.pid}.${Date.now()}`;fs.writeFileSync(t,JSON.stringify(users,null,2),'utf8');fs.renameSync(t,USERS_FILE);}
 private readSessions():Record<string,UserSession>{try{return JSON.parse(fs.readFileSync(SESSIONS_FILE,'utf8'));}catch{return{}}}
 private writeSessions(s:Record<string,UserSession>){const t=`${SESSIONS_FILE}.tmp.${process.pid}.${Date.now()}`;fs.writeFileSync(t,JSON.stringify(s,null,2),'utf8');fs.renameSync(t,SESSIONS_FILE);}
 private makeUser(p:{id:string;email:string;username:string;name:string;password:string;role:UserRole}):UserAccount{const now=new Date().toISOString();return{id:p.id,email:p.email.trim().toLowerCase(),username:p.username.trim().toLowerCase(),name:p.name.trim().slice(0,80),passwordHash:bcrypt.hashSync(p.password,bcrypt.genSaltSync(12)),role:p.role,createdAt:now,updatedAt:now,failedLoginAttempts:0,sessionVersion:0};}
 private seedInitialAccounts(){if(process.env.SEED_DEFAULT_ACCOUNTS!=='true')return;const username=(process.env.ADMIN_USER||'').trim().toLowerCase();const password=process.env.ADMIN_PASSWORD||'';if(!username||password.length<12)throw new Error('SEED_DEFAULT_ACCOUNTS=true requires ADMIN_USER and ADMIN_PASSWORD (minimum 12 characters).');const users=this.readUsers();let changed=false;if(!users.some(u=>u.username===username||u.role==='admin')){users.push(this.makeUser({id:`usr_admin_${nanoid(8)}`,username,email:process.env.ADMIN_EMAIL||'admin@prepielts.local',name:'Administrator',password,role:'admin'}));changed=true;}if(process.env.EXAMINER_SEED_PASSWORD&&!users.some(u=>u.username==='examiner')){users.push(this.makeUser({id:`usr_exam_${nanoid(8)}`,username:'examiner',email:process.env.EXAMINER_EMAIL||'examiner@prepielts.local',name:'IELTS Examiner',password:process.env.EXAMINER_SEED_PASSWORD,role:'examiner'}));changed=true;}if(changed)this.writeUsers(users);}
 private publicUser(user:UserAccount):Omit<UserAccount,'passwordHash'>{const{passwordHash:_passwordHash,...safe}=user;return safe;}
 private async invalidateFirestoreSessions(userId:string){const db=getFirestoreDb(),snap=await db.collection('auth_sessions').where('userId','==',userId).get();if(snap.empty)return;const batch=db.batch();snap.docs.forEach(d=>batch.delete(d.ref));await batch.commit();}
 private invalidateLocalSessions(userId:string){const s=this.readSessions();for(const [k,v]of Object.entries(s))if(v.userId===userId)delete s[k];this.writeSessions(s);}
 private localSession(user:UserAccount):UserSession{const token=`prep_${nanoid(48)}`,now=Date.now(),sessionVersion=user.sessionVersion||0;const s:UserSession={token,userId:user.id,username:user.username,email:user.email,name:user.name,role:user.role,createdAt:now,expiresAt:now+(user.role==='student'?SESSION_TTL_STUDENT_MS:SESSION_TTL_ADMIN_MS),sessionVersion};const sessions=this.readSessions();sessions[hashToken(token)]=s;this.writeSessions(sessions);return s;}
 private async firestoreSession(user:UserAccount){const token=`prep_${nanoid(48)}`,now=Date.now(),sessionVersion=user.sessionVersion||0;await getFirestoreDb().collection('auth_sessions').doc(hashToken(token)).set({userId:user.id,username:user.username,email:user.email,name:user.name,role:user.role,createdAt:now,expiresAt:now+(user.role==='student'?SESSION_TTL_STUDENT_MS:SESSION_TTL_ADMIN_MS),sessionVersion});return token;}
 public async register(p:{email:string;username:string;password:string;name?:string}){const email=String(p.email||'').trim().toLowerCase(),username=String(p.username||'').trim().toLowerCase(),password=String(p.password||'');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new AuthError('invalid_email');if(!/^[a-z0-9_.-]{3,32}$/.test(username))throw new AuthError('invalid_username');if(password.length<10||password.length>128)throw new AuthError('weak_password');if(useFirestoreAuth()){const db=getFirestoreDb(),id=`usr_${nanoid(16)}`,ref=db.collection('auth_users').doc(id),now=new Date().toISOString(),hash=bcrypt.hashSync(password,bcrypt.genSaltSync(12));await db.runTransaction(async tx=>{const e=await tx.get(db.collection('auth_users').where('email','==',email).limit(1));const u=await tx.get(db.collection('auth_users').where('username','==',username).limit(1));if(!e.empty||!u.empty)throw new AuthError('already_exists');tx.create(ref,{id,email,username,name:String(p.name||username).trim().slice(0,80),passwordHash:hash,role:'student',createdAt:now,updatedAt:now,failedLoginAttempts:0,sessionVersion:0});});const user=(await ref.get()).data() as UserAccount;return{user:this.publicUser(user),token:await this.firestoreSession(user)};}const users=this.readUsers();if(users.some(u=>u.username===username||u.email===email))throw new AuthError('already_exists');const user=this.makeUser({id:`usr_${nanoid(16)}`,email,username,name:String(p.name||username),password,role:'student'});users.push(user);this.writeUsers(users);return{user:this.publicUser(user),token:this.localSession(user).token};}
 public async login(identifier:string,password:string){const key=String(identifier||'').trim().toLowerCase();if(useFirestoreAuth()){const db=getFirestoreDb(),byU=await db.collection('auth_users').where('username','==',key).limit(1).get(),snap=!byU.empty?byU:await db.collection('auth_users').where('email','==',key).limit(1).get();if(snap.empty)throw new Error('Invalid credentials.');const ref=snap.docs[0].ref,user=snap.docs[0].data() as UserAccount,now=Date.now();if(user.lockoutUntil&&user.lockoutUntil>now)throw new Error('Too many login attempts. Please try again later.');if(!bcrypt.compareSync(String(password||''),user.passwordHash)){await db.runTransaction(async tx=>{const cur=await tx.get(ref),d=cur.data() as UserAccount,failed=(d.failedLoginAttempts||0)+1;tx.update(ref,{failedLoginAttempts:failed>=MAX_FAILED_ATTEMPTS?0:failed,lockoutUntil:failed>=MAX_FAILED_ATTEMPTS?now+LOCKOUT_DURATION_MS:FieldValue.delete(),updatedAt:new Date().toISOString()});});throw new Error('Invalid credentials.');}await ref.update({failedLoginAttempts:0,lockoutUntil:FieldValue.delete(),updatedAt:new Date().toISOString()});return{user:this.publicUser(user),token:await this.firestoreSession(user)};}const users=this.readUsers(),i=users.findIndex(u=>u.username===key||u.email===key);if(i<0)throw new Error('Invalid credentials.');const user=users[i],now=Date.now();if(user.lockoutUntil&&user.lockoutUntil>now)throw new Error('Too many login attempts. Please try again later.');if(!bcrypt.compareSync(String(password||''),user.passwordHash)){user.failedLoginAttempts=(user.failedLoginAttempts||0)+1;if(user.failedLoginAttempts>=MAX_FAILED_ATTEMPTS){user.failedLoginAttempts=0;user.lockoutUntil=now+LOCKOUT_DURATION_MS;}this.writeUsers(users);throw new Error('Invalid credentials.');}user.failedLoginAttempts=0;delete user.lockoutUntil;this.writeUsers(users);return{user:this.publicUser(user),token:this.localSession(user).token};}
 public async validateSession(token:string){if(!token)return null;if(useFirestoreAuth()){const db=getFirestoreDb(),ref=db.collection('auth_sessions').doc(hashToken(token)),snap=await ref.get();if(!snap.exists)return null;const s=snap.data() as Omit<UserSession,'token'>;if(s.expiresAt<=Date.now()){await ref.delete();return null;}const userSnap=await db.collection('auth_users').doc(s.userId).get();if(!userSnap.exists){await ref.delete();return null;}const user=userSnap.data() as UserAccount;if((user.sessionVersion||0)!==(s.sessionVersion||0)||user.role!==s.role){await ref.delete();return null;}return{...s,token} as UserSession;}const s=this.readSessions()[hashToken(token)];if(!s||s.expiresAt<=Date.now())return null;const user=this.readUsers().find(u=>u.id===s.userId);if(!user||((user.sessionVersion||0)!==(s.sessionVersion||0))||user.role!==s.role){this.invalidateLocalSessions(s.userId);return null;}return s;}
 public async logout(token:string){if(!token)return;if(useFirestoreAuth())await getFirestoreDb().collection('auth_sessions').doc(hashToken(token)).delete();else{const s=this.readSessions();delete s[hashToken(token)];this.writeSessions(s);}}
 public async getUserById(id:string){if(useFirestoreAuth()){const s=await getFirestoreDb().collection('auth_users').doc(id).get();return s.exists?this.publicUser(s.data() as UserAccount):null;}const u=this.readUsers().find(x=>x.id===id);return u?this.publicUser(u):null;}
 public async requestPasswordReset(email:string){const clean=String(email||'').trim().toLowerCase(),token=crypto.randomBytes(32).toString('base64url'),hash=hashToken(token),expiresAt=Date.now()+PASSWORD_RESET_TTL_MS;if(useFirestoreAuth()){const db=getFirestoreDb(),s=await db.collection('auth_users').where('email','==',clean).limit(1).get();if(s.empty)return{expiresMinutes:15};const user=s.docs[0].data() as UserAccount;if(process.env.NODE_ENV==='production'&&!isEmailDeliveryConfigured())throw new Error('Password reset email delivery is not configured.');await s.docs[0].ref.update({resetTokenHash:hash,resetTokenExpiresAt:expiresAt,updatedAt:new Date().toISOString()});if(isEmailDeliveryConfigured())await sendPasswordResetEmail({to:user.email,token});}else{const users=this.readUsers(),u=users.find(x=>x.email===clean);if(!u)return{expiresMinutes:15};if(process.env.NODE_ENV==='production'&&!isEmailDeliveryConfigured())throw new Error('Password reset email delivery is not configured.');u.resetTokenHash=hash;u.resetTokenExpiresAt=expiresAt;this.writeUsers(users);if(isEmailDeliveryConfigured())await sendPasswordResetEmail({to:u.email,token});}return{expiresMinutes:15,...(explicitDevAuth()?{resetToken:token}:{})};}
 public async resetPassword(email:string,token:string,newPassword:string){if(newPassword.length<10||newPassword.length>128)throw new Error('Invalid password.');const clean=String(email||'').trim().toLowerCase(),hash=hashToken(String(token||'')),now=Date.now();if(useFirestoreAuth()){const db=getFirestoreDb(),s=await db.collection('auth_users').where('email','==',clean).limit(1).get();if(s.empty)throw new Error('Invalid or expired reset token.');const ref=s.docs[0].ref,u=s.docs[0].data() as UserAccount;if(u.resetTokenHash!==hash||!u.resetTokenExpiresAt||u.resetTokenExpiresAt<=now)throw new Error('Invalid or expired reset token.');await db.runTransaction(async tx=>{const cur=await tx.get(ref),d=cur.data() as UserAccount;tx.update(ref,{passwordHash:bcrypt.hashSync(newPassword,bcrypt.genSaltSync(12)),resetTokenHash:FieldValue.delete(),resetTokenExpiresAt:FieldValue.delete(),sessionVersion:(d.sessionVersion||0)+1,updatedAt:new Date().toISOString()});});await this.invalidateFirestoreSessions(u.id);return;}const users=this.readUsers(),u=users.find(x=>x.email===clean);if(!u||u.resetTokenHash!==hash||!u.resetTokenExpiresAt||u.resetTokenExpiresAt<=now)throw new Error('Invalid or expired reset token.');u.passwordHash=bcrypt.hashSync(newPassword,bcrypt.genSaltSync(12));delete u.resetTokenHash;delete u.resetTokenExpiresAt;u.updatedAt=new Date().toISOString();u.sessionVersion=(u.sessionVersion||0)+1;this.writeUsers(users);this.invalidateLocalSessions(u.id);}
}
export const authService=new AuthService();
